allowed_schemes: ["vless", "vmess", "ss", "trojan"]

lite:
  strategy: per_host # per_host | first_n
  max_total: 100
  per_host_limit: 1
  n: 50

subscriptions:
  - key: "mahsaXray"
    url: "https://raw.githubusercontent.com/MahsaNetConfigTopic/config/refs/heads/main/xray_final.txt"
  - key: "code3Vless"
    url: "https://raw.githubusercontent.com/code3-dev/code3-dev/refs/heads/main/warp-in-vless#Warp-in-VLESS"
  - key: "parvinXs"
    url: "https://raw.githubusercontent.com/parvinxs/Submahsanetxsparvin/refs/heads/main/Sub.mahsa.xsparvin"
  - key: "psgDe"
    url: "https://raw.githubusercontent.com/itsyebekhe/PSG/main/lite/subscriptions/location/base64/DE"
  - key: "psgV6"
    url: "https://raw.githubusercontent.com/itsyebekhe/PSG/main/lite/subscriptions/xray/normal/vless_ipv6"
  - key: "amirAlter"
    url: "https://sub.amiralter.com/config-lite"
  - key: "darkProxy"
    url: "https://raw.githubusercontent.com/darkvpnapp/CloudflarePlus/refs/heads/main/proxy"
  - key: "psgMix"
    url: "https://raw.githubusercontent.com/itsyebekhe/PSG/main/lite/subscriptions/xray/normal/mix"
  - key: "hamedP"
    url: "https://cdn.jsdelivr.net/gh/hamedp-71/Sub_Checker_Creator@main/final.txt"
  - key: "soliSpirit"
    url: "https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/refs/heads/main/all_configs.txt"
  - key: "matinGh"
    url: "https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/super-sub.txt"
  - key: "daniSamadi"
    url: "https://raw.githubusercontent.com/Danialsamadi/v2go/main/All_Configs_Sub.txt"
